apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: {{ namespace }}
  annotations:
    metallb.universe.tf/address-pool: default-address-pool     # Optional: match your pool name
    metallb.universe.tf/allow-shared-ip: "ingress-nginx"       # If allowing IP sharing
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: ingress-nginx
