apiVersion: v1
kind: Service
metadata:
  name: keylime-ingress-lb
  namespace: {{ namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
