apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keylime-db
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keylime-db
  template:
    metadata:
      labels:
        app: keylime-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: keylime
        - name: POSTGRES_USER
          value: keylime
        - name: POSTGRES_PASSWORD
          value: keylime
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keylime-db
  namespace: {{ namespace }}
spec:
  selector:
    app: keylime-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP