apiVersion: v1
kind: Pod
metadata:
  name: agent-{{ agent_id }}
  namespace: {{ namespace }}
  labels:
    app: agent-{{ agent_id }}
    app.kubernetes.io/name: keylime-agent
spec:
  containers:
    - name: swtpm
      image: docker.io/danieltrick/swtpm-docker:r13
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      ports:
        - containerPort: 2321
        - containerPort: 2322
      volumeMounts:
        - name: tpm-state 
          mountPath: /tmp/mytpm1

    - name: tpm2-tools
      image: docker.io/svasala/tpm2-tools:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          apt-get update && apt-get install -y netcat &&
          while ! nc -zv 127.0.0.1 2321; do
            echo "Waiting for SWTPM on 2321...";
            sleep 2;
          done
          # Initialize TPM
          export TPM2TOOLS_TCTI="swtpm:host=127.0.0.1,port=2321" && \
          tpm2_startup -c && touch /tmp/mytpm1/tpm-initialized && echo "tpm2 startup succeeded"
          # --- Monitor Loop for Agent Error Signal ---
          while true; do
              echo "Running Context Flush..."
              #tpm2_flushcontext --transient-object --loaded-session --saved-session
              if [ -f /tmp/error-signal/flush_needed ]; then
                cat /tmp/error-signal/flush_needed
                rm -f /tmp/error-signal/flush_needed
                tpm2_flushcontext --transient-object --loaded-session --saved-session
              fi
              sleep 30
          done

      volumeMounts:
        - name: tpm-state
          mountPath: /tmp/mytpm1
        - name: error-signal
          mountPath: /tmp/error-signal
  
    - name: agent
      image: quay.io/keylime/keylime_agent
      command: ["/bin/sh", "-c"]
      args:
        - |
          # Wait for TPM to be initialized
          while [ ! -f /tmp/mytpm1/tpm-initialized ]; do
            echo "Waiting for TPM initialization...";
            sleep 2;
          done
          keylime_agent  2>&1 | tee /tmp/error-signal/agent.log &
          AGENT_PID=$!
          sleep 10

          # Simple monitor to detect TPM2_RC_OBJECT_MEMORY in logs
          while kill -0 $AGENT_PID 2>/dev/null; do
           if [ -f /tmp/error-signal/agent.log ] && grep -q "TPM2_RC_OBJECT_MEMORY" /tmp/error-signal/agent.log; then
             echo "tpm flush needed" > /tmp/error-signal/flush_needed
           fi
           sleep 5
          done

          wait $AGENT_PID
      readinessProbe:
        exec:
          command: ["test", "-f", "/tmp/mytpm1/tpm-initialized"]
        initialDelaySeconds: 5
        periodSeconds: 2
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        capabilities:
          add:
          - SYS_ADMIN
      env:
      - name: TPM_DEVICE
        value: "swtpm:host=127.0.0.1,port=2321"
      - name: TCTI
        value: "swtpm:host=127.0.0.1,port=2321"
      ports:
      - containerPort: 9002
      volumeMounts:
      - name: error-signal
        mountPath: /tmp/error-signal
      - name: tpm-state
        mountPath: /tmp/mytpm1
      - name: agent-config
        mountPath: /etc/keylime/agent.conf
        subPath: agent.conf
      - name: tls
        mountPath: /etc/keylime/tls
        readOnly: true
      - name: keylime-data
        mountPath: /var/lib/keylime
      resources:
        requests:
          memory: "512Mi"
          cpu: "400m"
        limits:
          memory: "1G"
          cpu: "800m"
  volumes:
  - name: tpm-state
    emptyDir: {}
  - name: agent-config
    configMap:
      name: agent-config-{{ agent_id }}
  - name: tls
    secret:
      secretName: agent-{{ agent_id }}-tls
  - name: keylime-data
    emptyDir: 
      medium: Memory
  - name: error-signal
    emptyDir: {}
